// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/f7c4e50fc1053dace974f97e545fde1dc06b9a6a/nanomsg/index.d.ts
declare module "nanomsg" {
  export interface EventCallback {
    (data: Buffer): void;
  }
  export class Socket {
    constructor(type: string, opts: Object);
    shutdown(addr: string): void;
    bind(addr: string): void;
    connect(addr: string): void;
    close(): void;
    send(buf: Buffer | string): number;
    on(event: string, cb: EventCallback): void;
  }
  export function socket(type: string, opts?: Object): Socket;
}
